name: widget_basicos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  qr_flutter: ^4.1.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  sqflite: ^2.0.0
  path: ^1.8.0
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  vibration: ^3.1.6
  battery_plus: ^7.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/ 
    - assets/images/ 
  fonts:
    - family: MyFuente
      fonts:
        - asset: assets/fonts/MyFuente.otf